[package]
name = "iced-minimal"
version = "0.1.0"
edition = "2021"

[dependencies]
iced = { branch = "master", git = "https://github.com/iced-rs/iced"  }
lilt = { path = "../../" }
iced_futures = "0.12.0"
